### ISSUE TITLE
500 due to InstantiationException

### ISSUE THREAD

**Issue by igorrosenberg** [igorrosenberg/grails-plugin-uml-class-diagram#4]
```
Caused by: java.lang.InstantiationException: 
	at grails.plugin.umlclassdiagram.UmlService.propertiesToSpec3(UmlService.groovy:203)
	at grails.plugin.umlclassdiagram.UmlService.extractArtefactData(UmlService.groovy:193)
	at grails.plugin.umlclassdiagram.UmlService$_getControllersAndServices_closure8_closure21.doCall(UmlService.groovy:176)
	at grails.plugin.umlclassdiagram.UmlService$_getControllersAndServices_closure8.doCall(UmlService.groovy:175)
	at grails.plugin.umlclassdiagram.UmlService.getControllersAndServices(UmlService.groovy:172)
	at grails.plugin.umlclassdiagram.UmlService.getPackageMap(UmlService.groovy:142)
	at grails.plugin.umlclassdiagram.UmlService.redirect(UmlService.groovy:24)
	at grails.plugin.umlclassdiagram.UmlController.draw(UmlController.groovy:32)
	... 9 more
```

**Comment by igorrosenberg** [comment]
`UmlService.propertiesToSpec3` is old code now. 

Can no longer reproduce.
